### ISSUE TITLE
pkg_resources.ContextualVersionConflict on fresh install

### ISSUE THREAD

**Issue by norbert-yoimo** [LeastAuthority/kubetop#34]
Arch linux

```
myuser /srv/http/stuff $ pip install --user kubetop
Collecting kubetop
  Downloading kubetop-17.4.17.1.tar.gz
Collecting bitmath (from kubetop)
  Downloading bitmath-1.3.1.2.tar.gz (166kB)
    100% |████████████████████████████████| 174kB 621kB/s 
Collecting attr (from kubetop)
  Downloading attr-0.2.0.tar.gz
Requirement already satisfied: pyyaml in /usr/lib/python3.6/site-packages (from kubetop)
Collecting twisted[tls] (from kubetop)
  Downloading Twisted-17.1.0.tar.bz2 (3.0MB)
    100% |████████████████████████████████| 3.0MB 395kB/s 
Collecting treq (from kubetop)
  Downloading treq-17.3.1-py2.py3-none-any.whl (41kB)
    100% |████████████████████████████████| 51kB 1.8MB/s 
Collecting txkube (from kubetop)
  Downloading txkube-0.1.0.tar.gz (124kB)
    100% |████████████████████████████████| 133kB 1.2MB/s 
Collecting zope.interface>=4.0.2 (from twisted[tls]->kubetop)
  Downloading zope.interface-4.4.0-cp36-cp36m-manylinux1_x86_64.whl (174kB)
    100% |████████████████████████████████| 184kB 1.4MB/s 
Collecting constantly>=15.1 (from twisted[tls]->kubetop)
  Downloading constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from twisted[tls]->kubetop)
  Downloading incremental-16.10.1-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from twisted[tls]->kubetop)
  Downloading Automat-0.5.0-py2.py3-none-any.whl
Collecting pyopenssl>=16.0.0 (from twisted[tls]->kubetop)
  Downloading pyOpenSSL-17.0.0-py2.py3-none-any.whl (51kB)
    100% |████████████████████████████████| 61kB 2.0MB/s 
Collecting service_identity (from twisted[tls]->kubetop)
  Downloading service_identity-16.0.0-py2.py3-none-any.whl
Collecting idna>=0.6 (from twisted[tls]->kubetop)
  Downloading idna-2.5-py2.py3-none-any.whl (55kB)
    100% |████████████████████████████████| 61kB 2.2MB/s 
Requirement already satisfied: requests>=2.1.0 in /home/myuser/.local/lib/python3.6/site-packages (from treq->kubetop)
Collecting attrs (from treq->kubetop)
  Using cached attrs-16.3.0-py2.py3-none-any.whl
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from treq->kubetop)
Collecting pyrsistent (from txkube->kubetop)
  Downloading pyrsistent-0.12.1.tar.gz (94kB)
    100% |████████████████████████████████| 102kB 1.7MB/s 
Collecting pem (from txkube->kubetop)
  Downloading pem-16.1.0-py2.py3-none-any.whl
Collecting eliot (from txkube->kubetop)
  Downloading eliot-1.0.0-py2.py3-none-any.whl (90kB)
    100% |████████████████████████████████| 92kB 1.2MB/s 
Requirement already satisfied: python-dateutil in /home/myuser/.local/lib/python3.6/site-packages (from txkube->kubetop)
Collecting pykube (from txkube->kubetop)
  Downloading pykube-0.15.0-py2.py3-none-any.whl
Collecting klein (from txkube->kubetop)
  Downloading klein-17.2.0-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/lib/python3.6/site-packages (from zope.interface>=4.0.2->twisted[tls]->kubetop)
Collecting cryptography>=1.7 (from pyopenssl>=16.0.0->twisted[tls]->kubetop)
  Downloading cryptography-1.8.1.tar.gz (423kB)
    100% |████████████████████████████████| 430kB 1.6MB/s 
Requirement already satisfied: pyasn1-modules in /home/myuser/.local/lib/python3.6/site-packages (from service_identity->twisted[tls]->kubetop)
Requirement already satisfied: pyasn1 in /home/myuser/.local/lib/python3.6/site-packages (from service_identity->twisted[tls]->kubetop)
Collecting tzlocal (from pykube->txkube->kubetop)
  Downloading tzlocal-1.4.tar.gz
Collecting requests-oauthlib (from pykube->txkube->kubetop)
  Downloading requests_oauthlib-0.8.0-py2.py3-none-any.whl
Requirement already satisfied: oauth2client in /home/myuser/.local/lib/python3.6/site-packages (from pykube->txkube->kubetop)
Collecting werkzeug (from klein->txkube->kubetop)
  Downloading Werkzeug-0.12.1-py2.py3-none-any.whl (312kB)
    100% |████████████████████████████████| 317kB 1.8MB/s 
Requirement already satisfied: packaging>=16.8 in /usr/lib/python3.6/site-packages (from setuptools->zope.interface>=4.0.2->twisted[tls]->kubetop)
Requirement already satisfied: appdirs>=1.4.0 in /usr/lib/python3.6/site-packages (from setuptools->zope.interface>=4.0.2->twisted[tls]->kubetop)
Collecting asn1crypto>=0.21.0 (from cryptography>=1.7->pyopenssl>=16.0.0->twisted[tls]->kubetop)
  Downloading asn1crypto-0.22.0-py2.py3-none-any.whl (97kB)
    100% |████████████████████████████████| 102kB 3.0MB/s 
Collecting cffi>=1.4.1 (from cryptography>=1.7->pyopenssl>=16.0.0->twisted[tls]->kubetop)
  Downloading cffi-1.10.0-cp36-cp36m-manylinux1_x86_64.whl (406kB)
    100% |████████████████████████████████| 409kB 1.2MB/s 
Collecting pytz (from tzlocal->pykube->txkube->kubetop)
  Downloading pytz-2017.2-py2.py3-none-any.whl (484kB)
    100% |████████████████████████████████| 491kB 1.2MB/s 
Collecting oauthlib>=0.6.2 (from requests-oauthlib->pykube->txkube->kubetop)
  Downloading oauthlib-2.0.2.tar.gz (125kB)
    100% |████████████████████████████████| 133kB 2.2MB/s 
Requirement already satisfied: httplib2>=0.9.1 in /home/myuser/.local/lib/python3.6/site-packages (from oauth2client->pykube->txkube->kubetop)
Requirement already satisfied: rsa>=3.1.4 in /home/myuser/.local/lib/python3.6/site-packages (from oauth2client->pykube->txkube->kubetop)
Requirement already satisfied: pyparsing in /usr/lib/python3.6/site-packages (from packaging>=16.8->setuptools->zope.interface>=4.0.2->twisted[tls]->kubetop)
Collecting pycparser (from cffi>=1.4.1->cryptography>=1.7->pyopenssl>=16.0.0->twisted[tls]->kubetop)
  Downloading pycparser-2.17.tar.gz (231kB)
    100% |████████████████████████████████| 235kB 1.8MB/s 
Installing collected packages: bitmath, attr, zope.interface, constantly, incremental, attrs, Automat, idna, asn1crypto, pycparser, cffi, cryptography, pyopenssl, service-identity, twisted, treq, pyrsistent, pem, eliot, pytz, tzlocal, oauthlib, requests-oauthlib, pykube, werkzeug, klein, txkube, kubetop
  Running setup.py install for bitmath ... done
  Running setup.py install for attr ... done
  Running setup.py install for pycparser ... done
  Running setup.py install for cryptography ... done
  Running setup.py install for twisted ... done
  Running setup.py install for pyrsistent ... done
  Running setup.py install for tzlocal ... done
  Running setup.py install for oauthlib ... done
  Running setup.py install for txkube ... done
  Running setup.py install for kubetop ... done
Successfully installed Automat-0.5.0 asn1crypto-0.22.0 attr-0.2.0 attrs-16.3.0 bitmath-1.3.1.2 cffi-1.10.0 constantly-15.1.0 cryptography-1.8.1 eliot-1.0.0 idna-2.5 incremental-16.10.1 klein-17.2.0 kubetop-17.4.17.1 oauthlib-2.0.2 pem-16.1.0 pycparser-2.17 pykube-0.15.0 pyopenssl-17.0.0 pyrsistent-0.12.1 pytz-2017.2 requests-oauthlib-0.8.0 service-identity-16.0.0 treq-17.3.1 twisted-17.1.0 txkube-0.1.0 tzlocal-1.4 werkzeug-0.12.1 zope.interface-4.4.0
```
```
myuser /srv/http/stuff $ kubetop
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Twisted 17.1.0 (/home/myuser/.local/lib/python3.6/site-packages), Requirement.parse('twisted[tls]!=17.1.0'), {'txkube'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myuser/.local/bin/kubetop", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 656, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 669, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 859, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (Twisted 17.1.0 (/home/myuser/.local/lib/python3.6/site-packages), Requirement.parse('twisted[tls]!=17.1.0'), {'txkube'})
```

**Comment by exarkun** [comment]
Hrm. :/

kubetop excludes Twisted 17.1.0 because of a regression in the HTTP client.  Apparently this means of exclusion isn't reliable though.  I had some vague notion that this was the case but I thought that it would be safe to use in an application being installed in its own virtualenv.  Apparently not...

**Comment by exarkun** [comment]
I'm not able to reproduce this on Python 2.7 (perhaps pip3 deals with pkg_resources / entrypoints differently?  I don't know) but I tried duplicating the txkube Twisted exclusion in kubetop, perhaps that will help.

**Comment by norbert-yoimo** [comment]
I was trying with python 3 initially, I didn't see it mentioned anywhere that this is a python2 project, but I see it in another issue now.
