### ISSUE TITLE
Doesn't work in Python 3

### ISSUE THREAD

**Issue by gjcarneiro** [LeastAuthority/kubetop#37]
```
Traceback (most recent call last):
  File "/home/gjc/.virtualenvs/py3/bin/kubetop", line 7, in <module>
    from kubetop._script import main
  File "/home/gjc/.virtualenvs/py3/lib/python3.6/site-packages/kubetop/_script.py", line 27, in <module>
    from ._textrenderer import Sink, kubetop
  File "/home/gjc/.virtualenvs/py3/lib/python3.6/site-packages/kubetop/_textrenderer.py", line 114
    def _render_pod_top(reactor, (node_info, pod_info)):
                                 ^
SyntaxError: invalid syntax
```

**Comment by exarkun** [comment]
Thanks.  Indeed.  This was filed previously as #30
