### ISSUE TITLE
SyntaxError after install

### ISSUE THREAD

**Issue by TheoBrigitte** [LeastAuthority/kubetop#67]
I installed `kubetop` using the following command `sudo pip install kubetop`, which installed `kubetop` version `17.4.17.1` and its dependencies.

When I try to run `kubetop` it crashes and show the following error:
```
$ kubetop
Traceback (most recent call last):
  File "/usr/bin/kubetop", line 11, in <module>
    load_entry_point('kubetop==17.4.17.1', 'console_scripts', 'kubetop')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/kubetop/_script.py", line 27, in <module>
    from ._textrenderer import Sink, kubetop
  File "/usr/lib/python3.7/site-packages/kubetop/_textrenderer.py", line 114
    def _render_pod_top(reactor, (node_info, pod_info)):
                                 ^
SyntaxError: invalid syntax
```

I am running archlinux and Python 3.7.1.

**Comment by exarkun** [comment]
Only Python 2.7 is currently supported.  If someone wants to port kubetop to Python 3, contributions are welcome.

**Comment by TheoBrigitte** [comment]
I re-installed `kubetop` using Python 2.7.15

I am now running into a different error:
```
$ kubetop
Traceback (most recent call last):
--- <exception caught here> ---
  File "/usr/lib/python2.7/site-packages/kubetop/_runmany.py", line 33, in _iterate
    yield f()
twisted.internet.defer.FirstError: FirstError[#1, [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.defer.FirstError'>: FirstError[#1, [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'schedulerName, enableServiceLinks, priority, tolerations' are not among the specified fields for v1.PodSpec
/usr/lib/python2.7/site-packages/twisted/web/_newclient.py:1229:_bodyDataFinished_CONNECTED
/usr/lib/python2.7/site-packages/twisted/web/client.py:2170:connectionLost
/usr/lib/python2.7/site-packages/twisted/internet/defer.py:460:callback
/usr/lib/python2.7/site-packages/twisted/internet/defer.py:568:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python2.7/site-packages/twisted/internet/defer.py:654:_runCallbacks
/usr/lib/python2.7/site-packages/eliot/twisted.py:83:callbackWithContext
/usr/lib/python2.7/site-packages/eliot/_action.py:402:run
/usr/lib/python2.7/site-packages/txkube/_network.py:394:<lambda>
/usr/lib/python2.7/site-packages/pyrsistent/_helpers.py:80:inner_f
/usr/lib/python2.7/site-packages/txkube/_model.py:95:iobject_from_raw
/usr/lib/python2.7/site-packages/pyrsistent/_pclass.py:125:create
/usr/lib/python2.7/site-packages/txkube/_swagger.py:760:discard_constant_fields
/usr/lib/python2.7/site-packages/txkube/_swagger.py:758:ctor
/usr/lib/python2.7/site-packages/txkube/_model.py:261:__new__
/usr/lib/python2.7/site-packages/pyrsistent/_pclass.py:54:__new__
/usr/lib/python2.7/site-packages/pyrsistent/_checked_types.py:267:_checked_type_create
/usr/lib/python2.7/site-packages/pyrsistent/_pclass.py:125:create
/usr/lib/python2.7/site-packages/txkube/_swagger.py:760:discard_constant_fields
/usr/lib/python2.7/site-packages/txkube/_swagger.py:758:ctor
/usr/lib/python2.7/site-packages/pyrsistent/_pclass.py:54:__new__
/usr/lib/python2.7/site-packages/txkube/_swagger.py:348:optional
/usr/lib/python2.7/site-packages/pyrsistent/_pclass.py:125:create
/usr/lib/python2.7/site-packages/txkube/_swagger.py:760:discard_constant_fields
/usr/lib/python2.7/site-packages/txkube/_swagger.py:758:ctor
/usr/lib/python2.7/site-packages/pyrsistent/_pclass.py:71:__new__
]]
]]
```

**Comment by Huge** [comment]
> I re-installed `kubetop` using Python 2.7.15

I get the same with Python 2.7.16 , installed with `pipsi` obtained with `pip2`.
